GET http://localhost:8000/crystals

###

GET http://localhost:8000/crystals/62d2d87a6828474b80b402de

###

POST http://localhost:8000/crystals
Content-Type: application/json
    
{
     "name": "RoseQuartz",
    "color": "Pink",
    "chakra": "Heart"
}

###

DELETE  http://localhost:8000/crystals/62d1aae19f9711a74d702bae

###

PATCH http://localhost:8000/crystals/62d2d87a6828474b80b402de
Content-Type: application/json
    
{
    "name": "Rose Quartz",
    "color": "Pink",
    "chakra": "Heart"
}