GET http://localhost:8000/crystals

###

GET http://localhost:8000/crystals

###

POST http://localhost:8000/crystals
Content-Type: application/json
    
{
    "name": "Amethyst ",
    "color": "Purple",
    "chakra": "Crown"
}

###

DELETE  http://localhost:8000/crystals

###

PATCH http://localhost:8000/crystals
Content-Type: application/json
    
{
    "name": "Moonstone",
    "color": "White",
    "chakra": "Crown"
}